import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "boom-chick",
    name: "Boom-chick",
    blurb: "Bass on 1 and 3. Open chord on 2 and 4. The country bed AI never writes.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "boom-chick",
  },
  {
    id: "open-strum",
    name: "Open strum",
    blurb: "Downstrokes on the beat, light ups on the ands. Steel rings, not a pad.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "open-strum",
  },
  {
    id: "travis",
    name: "Travis pick",
    blurb: "Alternating bass, fingers on the treble. The verse finally has a chair.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "travis",
  },
  {
    id: "folk-8ths",
    name: "Folk 8ths",
    blurb: "Even downstrokes. No mute, no chicka. This is the folk bed.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "folk-8ths",
  },
  {
    id: "chuck",
    name: "Chuck 2+4",
    blurb: "Open on 1. Muted chuck on 2 and 4. Space on 3. Not ChickFour.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 1,
    feel: "chuck",
  },
  {
    id: "hammer",
    name: "Hammer figure",
    blurb: "Open chord, then a hammered 3rd on the and of two. Tiny live move.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "hammer",
  },
  {
    id: "last-fill",
    name: "Last-bar fill",
    blurb: "Boom-chick for three. Bar 4 is a live run into the next section.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 3,
    feel: "last-fill",
  },
  {
    id: "camp",
    name: "Camp whole",
    blurb: "One live strum per bar. Air between. The vocal can sit.",
    lowFrom: 0,
    midFrom: 0,
    highFrom: 0,
    feel: "camp",
  },
];
